export const MAX_SIZE = {
  landscape: {
    width: 2796,
    height: 2084,
  },
  portrait: {
    width: 2084,
    height: 2796,
  },
};

export const SPLASH_IMAGES = [
  {
    name: "4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape",
    orientation: "landscape",
    width: 1366,
    height: 640,
  },
  {
    name: "4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait",
    orientation: "portrait",
    width: 640,
    height: 1366,
  },
  {
    name: "8.3__iPad_Mini_landscape",
    orientation: "landscape",
    width: 2266,
    height: 1488,
  },
  {
    name: "8.3__iPad_Mini_portrait",
    orientation: "portrait",
    width: 1488,
    height: 2266,
  },
  {
    name: "9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape",
    orientation: "landscape",
    width: 2048,
    height: 1536,
  },
  {
    name: "9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait",
    orientation: "portrait",
    width: 1536,
    height: 2048,
  },
  {
    name: "10.2__iPad_landscape",
    orientation: "landscape",
    width: 2160,
    height: 1620,
  },
  {
    name: "10.2__iPad_portrait",
    orientation: "portrait",
    width: 1620,
    height: 2160,
  },
  {
    name: "10.5__iPad_Air_landscape",
    orientation: "landscape",
    width: 2224,
    height: 1668,
  },
  {
    name: "10.5__iPad_Air_portrait",
    orientation: "portrait",
    width: 1668,
    height: 2224,
  },
  {
    name: "10.9__iPad_Air_landscape",
    orientation: "landscape",
    width: 2360,
    height: 1640,
  },
  {
    name: "10.9__iPad_Air_portrait",
    orientation: "portrait",
    width: 1640,
    height: 2360,
  },
  {
    name: "11__iPad_Pro__10.5__iPad_Pro_landscape",
    orientation: "landscape",
    width: 2388,
    height: 1668,
  },
  {
    name: "11__iPad_Pro__10.5__iPad_Pro_portrait",
    orientation: "portrait",
    width: 1668,
    height: 2388,
  },
  {
    name: "12.9__iPad_Pro_landscape",
    orientation: "landscape",
    width: 2732,
    height: 2084,
  },
  {
    name: "12.9__iPad_Pro_portrait",
    orientation: "portrait",
    width: 2084,
    height: 2732,
  },
  {
    name: "iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape",
    orientation: "landscape",
    width: 1334,
    height: 750,
  },
  {
    name: "iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait",
    orientation: "portrait",
    width: 750,
    height: 1334,
  },
  {
    name: "iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape",
    orientation: "landscape",
    width: 2208,
    height: 1242,
  },
  {
    name: "iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait",
    orientation: "portrait",
    width: 1242,
    height: 2208,
  },
  {
    name: "iPhone_11__iPhone_XR_landscape",
    orientation: "landscape",
    width: 1792,
    height: 828,
  },
  {
    name: "iPhone_11__iPhone_XR_portrait",
    orientation: "portrait",
    width: 828,
    height: 1792,
  },
  {
    name: "iPhone_11_Pro_Max__iPhone_XS_Max_landscape",
    orientation: "landscape",
    width: 2688,
    height: 1242,
  },
  {
    name: "iPhone_11_Pro_Max__iPhone_XS_Max_portrait",
    orientation: "portrait",
    width: 1242,
    height: 2688,
  },
  {
    name: "iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape",
    orientation: "landscape",
    width: 2436,
    height: 1125,
  },
  {
    name: "iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait",
    orientation: "portrait",
    width: 1125,
    height: 2436,
  },
  {
    name: "iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape",
    orientation: "landscape",
    width: 2532,
    height: 1170,
  },
  {
    name: "iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait",
    orientation: "portrait",
    width: 1170,
    height: 2532,
  },
  {
    name: "iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape",
    orientation: "landscape",
    width: 2778,
    height: 1284,
  },
  {
    name: "iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait",
    orientation: "portrait",
    width: 1284,
    height: 2778,
  },
  {
    name: "iPhone_14_Pro_landscape",
    orientation: "landscape",
    width: 2556,
    height: 1179,
  },
  {
    name: "iPhone_14_Pro_Max_landscape",
    orientation: "landscape",
    width: 2796,
    height: 1290,
  },
  {
    name: "iPhone_14_Pro_Max_portrait",
    orientation: "portrait",
    width: 1290,
    height: 2796,
  },
  {
    name: "iPhone_14_Pro_portrait",
    orientation: "portrait",
    width: 1179,
    height: 2556,
  },
];
